### ISSUE TITLE
[Feat] MapView Object Animation 구현 하기

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#10]
### 📝 작업 목적 / Miro / Figma

- MapView 내의 객체 들의 애니메이션 들을 구현합니다.
    - 객체들의 호흡 애니메이션 구현
    - 객체들의 이동 애니메이션 구현
---

### 🛠️ Tasks

* [x] 객체들의 호흡 애니메이션 구현
* [x] 객체들의 이동 애니메이션 구현
* [x] 프로젝트 구조에 따른 코드 분리
