### ISSUE TITLE
[Feat] DailySleep 관련 CoreData 메소드 로직 및 플로우 전체 개선

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#104]
### 📝 작업 목적 / Miro / Figma

- 파생 이슈: #102 , #97 
- DailySleep 내부 메소드 정리 및 호출 시점을 외부에서 컨트롤 할 수 있도록 정리
    - `processStatus` 및 시간 정리 등의 호출 시점오류 정리
    - 기존 호출위치 파악 후 정리

---

### 🛠️ Tasks

* [x] 함수형 CoreData > DailySleep 업데이트
    * [x] 각 메소드가 호출되는 시점 파악 및 정리
    * [x] 서브 브랜치 관리 필수
