### ISSUE TITLE
[Feat] Animation Gradient Background를 구현합니다.

### ISSUE THREAD

**Issue by pscu91** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#11]
### 📝 작업 목적

- 파생 작업: #7 
- Animation Gradient Background의 구현

---

### 🛠️ Tasks

* [x] Gradient Background 적용
* [x] Animation 적용
* [x] Time Coredata를 통한 배경색 자동 변환 구현
* [x] Color Theme에 따라 반영
