### ISSUE TITLE
[Feat] CoreData Time Setting 및 관련 버그 수정

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#111]
### 📝 작업 목적 / Miro / Figma

1. Sleep Time Setting을 진행할 때, 이전에 선택한 날짜가 있다면 해당 날짜로 Time picker가 init 되도록 수정
2. Sleep Time Setting, Notification Setting을 Main의 Toolbar button으로 하도록 수정

---

### 🛠️ Tasks

* [x] Sleep Time Setting
    * [x] CoreData 에서 UserSleepConfig의 시간을 가져오기
    * [x] 해당 시간의 `.hour`, `.minute`을 지정하기
* [x] Main View
    * [x] 수정된 MainView UI Impl
    * [x] Setting Menu Impl
    * [x] Asset Add
