### ISSUE TITLE
[Feat/Design] 톱니바퀴 원형 Button에 쓰일 Asset을 Figma에 작업합니다.

### ISSUE THREAD

**Issue by pscu91** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#114]
### 📝 작업 목적 / Miro / Figma

- 톱니바퀴 원형 Button에 쓰일 Asset을 Figma에 작업합니다.

---

### 🛠️ Tasks

* [x] 톱니바퀴 Pixel Art화 작업.
* [x] Figma 컴포넌트화 작업
* [x] Design System TabButton 섹션에 반영

### 작업물
<img width="169" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/91787174/f527a6ee-a22c-40c3-8984-27b88c990865">
