### ISSUE TITLE
[Feat] 계란 Gesture, Animation, Interaction을 구현합니다.

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#16]
### 📝 작업 목적 / Miro / Figma

계란 Drag gesture를 비롯한 여러 Gesture, Animation, Interaction을 구현합니다.
---

### 🛠️ Tasks

* #33 
* [x] 살랑살랑 애니메이션
* [x] Drag gesture 구현
    * [x] 벽에 막히게 하기
    * [x] 벽에 부딪히면 햅틱
    * [x] 알 잡고 있으면 멈춰있는 롱제스처 추가
* #22
