### ISSUE TITLE
[Feat] 알 그리면 알 나오는 제스처 및 애니메이션을 구현합니다.

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#33]
### 📝 작업 목적 / Miro / Figma

- #16 의 하위 이슈입니다.
알 그리면 알 나오는 제스처 및 애니메이션을 구현합니다.

---

### 🛠️ Tasks

* [x] 알을 흰선으로 그리는 기능 구현
* [x] 알을 다 그리면 알 이미지 나오기
* [x] 그릴 때 반짝이 도트 나오기
    - #44

**Comment by ValseLee** [comment]
이슈에 Assignees 꼭 지정해주세여
그리고 시간 내에 구현 어려울 것 같으면 꼭 미리 공유 주세요!
