### ISSUE TITLE
TextField

### ISSUE THREAD

**Issue by Gxxunx** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#38]

**Comment by Gxxunx** [comment]
### 📝 작업 목적 / Miro / Figma

- #5 의 하위 이슈입니다!
유저들의 텍스트를 입력받을 Text field를 구현합니다.

---

### 🛠️ Tasks

* [ ] 텍스트 필드 구현
* [ ] 디자인 시스템에 맞춰서 Custom
* [ ] 버튼 액션으로 작업 완료하게 만들기
