### ISSUE TITLE
[Feat] Calendar Customizing

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#4]
### 📝 작업 목적 / Miro / Figma

- Calendar 커스터마이징
- CalendarView Logic Implement
    - 날짜를 수면상태와 동물들 관련 정보로 동그라미 체크 구현

---

### 🛠️ Tasks

* [ ] CalendarView 커스터마이징
* [ ] CalendarView Login 구현
    * [ ] 날짜 체크 기능
    * [ ] CoreData에 사용자 체크 내용 저장

**Comment by ValseLee** [comment]
Hi-fi 나오면 다시 진행
