### ISSUE TITLE
[Feat] 알 제스처에 관한 파티클 이펙트 및 햅틱 효과를 구현합니다.

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#44]
### 📝 작업 목적 / Miro / Figma

- 알 그림 그릴 때 반짝이 파티클 이펙트를 구현합니다.
- 알 애니메이션 및 드래그 제스처가 실행될 때의 햅틱 효과를 구현합니다.    
- 관련 상위 이슈들
    - #16 
    - #33 
---

### 🛠️ Tasks

* [ ] EggDrawGesture에 파티클 이펙트 구현
* [ ] EggAnimation에 다양한 햅틱 적용하기
* [ ] EggAnimation의 함수 리팩토링

**Comment by SeBin-Kwon** [comment]
프로젝트 파일 이슈로 인해 아래 이슈로 이동함.
- #55
