### ISSUE TITLE
[Feat] UT Ver 에 Logic 을 연결합니다.

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#45]
### 📝 작업 목적 / Miro / Figma

1. 기본 Logic 을 더하여 앱의 Keyflow를 구현합니다.

---

### 🛠️ Tasks

* [ ] #52
* [ ] Core Data
  * [ ] User's Daily Sleep > Character, Date, etc
  * [x] User's SleepRoutine > Sleep Time, Notification Message
* [ ] Lock Screen > Unlock Screen Time Tracking
* [x] Navigation
