### ISSUE TITLE
[Feat] DreamPetBirthView 구현

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#60]
### 📝 작업 목적 / Miro / Figma

User가 일어난 뒤, 드림펫이 태어나는 것을 확인하는 DreamPetBirthView를 구현합니다.
화면 전환과 애니메이션, 햅틱 피드백등을 추가합니다.
---

### 🛠️ Tasks

* [ ] DreamPetBirthView 생성
* [ ] 화면 전환 구현
* [ ] 알 태동 Animation 추가
* [ ] 알 태동 Haptic Feedback 추가
