### ISSUE TITLE
[Feat/Design] AwakeView의 Egg를 더욱 반짝이게 합니다.

### ISSUE THREAD

**Issue by pscu91** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#67]
### 📝 작업 목적 / Miro / Figma
- #56 에서 파생 된 작업
- Egg 이미지가 더욱 빛날 수 있게 표현합니다.

---

### 🛠️ Tasks

* [x] Egg 이미지 위에 반짝이는 파티클을 얹습니다.
  * [x] 가능하다면 애니메이션도 넣어봅니다.
    * [x] Egg의 수면 상태를 표현 한 'Zzz...'에도 넣어봅니다.
