### ISSUE TITLE
[Feat] LofiMainEggView의 transition 구현 및 방석 이미지 추가, 뒤로 가는 기능 추가

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#68]
### 📝 작업 목적 / Miro / Figma

- MainView -> DrawView로 갈 때, emptyEgg image의 transition 및 animation 구현
- MainView의 방석 이미지 추가
---

### 🛠️ Tasks

* [x] emptyEgg image의 transition 및 animation 구현
* [x] 방석 이미지 추가
* [x] LofiEggDrawView에 뒤로가는 기능 추가
* [x] LofiBirthView에 뒤로가는 기능 추가
