### ISSUE TITLE
[Feat]Image Assets 추가

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#71]
### 📝 작업 목적 / Miro / Figma

 이전 issue 에서 추가하려 했던 베개 이미지를 추가하지 않고 머지를 진행하여서 해당 작업을 이슈로 새로 만들었습니다.
---

### 🛠️ Tasks

* [ ] 베개 이미지 추가
* [ ] 코끼리 이미지 1 추가
* [ ] 코끼리 이미지 2 추가
* [ ] 코끼리 정면 얼굴 이미지 추가
