### ISSUE TITLE
[Feat] 알 품기 실패 시의 화면을 작업합니다.

### ISSUE THREAD

**Issue by pscu91** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#76]
### 📝 작업 목적 / Miro / Figma
- #75 에서 파생
- UT용 로직을 만드려고 했으나, 기존에 실패 시의 화면이 존재하지 않았음.

---

### 🛠️ Tasks

* [x] @eratchacha가 기 작업한 `LofiBirthView`을 참고하여 작업합니다.
  * [x] 기존 탭하여 step을 넘기던 방식이 아니라, 자동으로 넘어가게끔 변경합니다.
  * [x] `LofiBirthView` 화면과 레이아웃을 일치시킵니다.
