### ISSUE TITLE
[Feat] DETextField에 추가 기능들을 만듭니다.

### ISSUE THREAD

**Issue by Gxxunx** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#79]
### 📝 작업 목적 / Miro / Figma

현재 DETextField에서 UT전 건의된 추가 사항들을 반영합니다.

---

### 🛠️ Tasks

* [ ] 문장형에 맞는 크기 수정
* [ ] 텍스트 최대 글자수 제한 기능 구현
* [ ] 텍스트 클리어 버튼 추가
