### ISSUE TITLE
[Sprint4 Todo]

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#97]
## 개발
* [ ] LofiSleepGuideView 수면 유도활동에서 버튼 삭제하고 자동으로 넘어가는 라벨 애니메이션 - 비니
* [ ] 캘린더 디테일 뷰에 Back버튼 필요 혹은 스와이프해서 뒤로 가게 하기
* [ ] 알에서 드림펫 태어났을 때, 계속 탭을 해야지만 넘어가져서 약간 불편한 문제 
-> 자동으로 넘어가는 라벨 애니메이션 넣는게 좋을듯

## 개발 + 디자인
* [ ] 버튼, 네비게이션 컴포넌트 적용
* [ ] 폰트 크기, 행간, 자간, 색상 등 가독성 디벨롭 및 컴포넌트 적용 
* [ ] 알에서 드림펫 태어나려고 할 때, 마찬가지로 탭해야 넘어가는데 유저는 이를 몰라서 보고 기다리고 있음
-> 자동으로 알에서 태어나거나 아예 탭을 막해서 알을 깨는 느낌으로 가야할 듯 + 햅틱 좀 더 부드러운걸로

## 디자인
* [ ] 동물 + 알 도트 이미지 추가(동물 색깔 별로 종류 뻥튀기 하기)
* [ ] 버튼 디자인 수정(disable처럼 보이는 문제)
