### ISSUE TITLE
[Feat] 현재 까지의 작업 결과 확인 및 수정

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#98]
### 📝 작업 목적 / Miro / Figma

- 우선 현재까지 머지된 코드들을 살펴보고 수정해야 할 부분이 있나 확인 후, 수정을 진행하여 토->일에 실시된 자체 UT를 준비하려고 합니다.
- 현재 이슈로 만들어 놓은 사항들은 테스크로 기록하지 않았습니다.
---

### 🛠️ Tasks
- Task는 Figma와 코드를 같이 살펴 본 뒤 작성하고 수정하도록 하겠습니다.
* [x] LofiBirthView에서 LofiNameConfirmView로의 NavigationLink에서 LofiNameConfirmView에 Binding 변수가 주석 처리 되었는데 변수를 넘겨줍니다.
    * [x] 위의 에러 해결 후 DECalendarTestView의 생성자에서 confirmedName을 초기화 해주지 않아 에러가 발생합니다.
* [x] DECalendarTestView Core Data와 연결
    * [x] DECalendarTestView에 This Week Section과 이번 주 Section이 같이 나타나는 현상 - 더미데이터 (This Week 항목의 쿼카 데이터) 삭제 
* [ ] #100
    * [ ] #101
* [x] LofiEggInteractionView Core Data와 연결 (Egg Image)
* [x] LofiAwakeView Core Data와 연결 (Egg Image)
* [x] LofiAwakeView 에서의 NavigationLink 미 작동
* [ ] LofiAwakeView 성공 로직에서 좌상단에서 파티클 효과가 날아옴. -> 의도된 바인가요?
* [x] LofiBirthView에서 Egg Image가 보이지 않음. (현재 Empty String이 연결되어 있음.)
* [ ] #102
* [x] LofiNamingConfirmView에서 DreamPet Image가 보이지 않음.
* [ ] 시간 수정 뷰에 들어갔다 나올 때 maineggview가 아닌 calendarview로 전환 -> 지속적으로 발생하는 것은 X
* [ ] 시간 수정 뷰에서 시간 설정 후 내일 나에게 할 말 뷰로 넘어감 -> 지속적으로 발생하는 것은 X
